---
name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Install node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '14'
      - name: Compile
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Snyk authenticate
        run: yarn run security:auth ${{ secrets.SNYK_API_TOKEN }}
      - name: Unit tests
        run: yarn run test
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        version: ['0.3.0']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - name: Install node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '14'
      - name: Compile
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Install {PROJECT_TITLE}
        uses: fabasoad/{PROJECT_NAME}@v1.0.0
        with:
          version: ${{ matrix.version }}
      - name: Run script (Linux, MacOS)
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: {PROJECT_CLI} ./{PROJECT_SCRIPT_FILE}
      - name: Run script (Windows)
        if: matrix.os == 'windows-latest'
        run: {PROJECT_CLI}-${{ matrix.version }}.exe ./{PROJECT_SCRIPT_FILE}
