---
name: CI (latest)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  unit_tests:
    name: Unit Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn run lint
      - run: yarn run test
