---
name: Lint

on: push

jobs:
  yaml_lint:
    name: YAML Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ibiqlik/action-yamllint@v3.0.0
        with:
          config_file: .yamllint.yml
          strict: false
  markdown_lint:
    name: Markdown Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
  makefile_lint:
    name: Makefile Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    container: docker.pkg.github.com/mrtazz/checkmake/checkmake:f127301db6ce6d9861ea0c9b94cd08a9d023fb77
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Lint
        run: checkmake Makefile
